app: {
    // Customize how your 'site' and 'locale' are displayed in the url.
    url: {
        // Determine where the siteRef is located. Valid values include 'path|query_param|none'. Defaults to: 'none'
        // site: 'none',
        // Determine where the localeRef is located. Valid values include 'path|query_param|none'. Defaults to: 'none'
        locale: 'none',
        // This boolean value dictates whether or not default site or locale values are shown in the url. Defaults to: false
        // showDefaults: true
    },

    // The default site for your app. This value will be used when a siteRef could not be determined from the url
    defaultSite: 'RefArch',
    // Provide aliases for your sites. These will be used in place of your site id when generating paths throughout the application.
    // siteAliases: {
    // RefArch: 'us'
    // },
    // The sites for your app, which is imported from sites.js
    sites,
    // Commerce api config
    commerceAPI: {
        proxyPath: `/mobify/proxy/api`,
        parameters: {
            clientId: '1d763261-6522-4913-9d52-5d947d3b94c4',
            organizationId: 'f_ecom_zzte_053',
            shortCode: 'kv7kzm78',
            siteId: 'RefArch'
        }
    },

    // Einstein api config
    einsteinAPI: {
        host: 'https://api.cquotient.com',
        einsteinId: '',
        siteId: '',
        // Flag Einstein activities as coming from a production environment.
        // By setting this to true, the Einstein activities generated by the environment will appear
        // in production environment reports
        isProduction: false
    }
}